// Single source of truth for Supabase types across web + mobile.
// `database.types.ts` is GENERATED by `supabase gen types` (root `db:types` script) —
// NEVER hand-edit it. Add convenience aliases below, reusing the generated helpers.

export * from './database.types';
// Explicit re-export guards the two externally-consumed names against `export *`
// silently dropping them on a future name collision.
export type { Json, Database } from './database.types';

import type { Tables } from './database.types'; // reuse the GENERATED helper (do not redefine)
export type MenuItemRow = Tables<'menu_items'>;
